spring:
  application:
    name: barber-shop-api
  datasource:
    url: jdbc:postgresql://localhost:5432/barber-shop-api
    username: barber-shop-api
    password: barber-shop-api
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate