services:
  app:
    build:
      context: .
    command: bash start-dev.sh
    environment:
      DB_URL: jdbc:postgresql://db:5432/barber-shop-api
      DB_USER: barber-shop-api
      DB_PASSWORD: barber-shop-api
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/barber-shop-api:z
    depends_on:
      db:
        condition: service_healthy
    networks:
      - barber-shop-net
  db:
    image: postgres:16.8
    environment:
      POSTGRES_USER: barber-shop-api
      POSTGRES_PASSWORD: barber-shop-api
      POSTGRES_DB: barber-shop-api
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - barber-shop-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U barber-shop-api"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  barber-shop-net:
    name: barber-shop-net
volumes:
  db-data: